### ISSUE TITLE
Deserialize JsonSerializationException: Cannot deserialize the current JSON object

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Bybit.Net#13]
Hello,
By giving symbol parameter via `InversePerpetualApi`, a **JsonSerialize error** is received for which position information is requested. However, when the symbol parameter is not given, the query works properly.

The code block below throws an error:
`var positionResult = await client.InversePerpetualApi.Account.GetPositionsAsync("BITUSD").ConfigureAwait(false);`

The code block below is working correctly:
`var positionResult = await client.InversePerpetualApi.Account.GetPositionsAsync().ConfigureAwait(false);`

Error details:
====================

**Version:** 0.0.1-beta7

Deserialize JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[Bybit.Net.Objects.Internal.BybitPositionData]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'result.id', line 1, position 72.

**Comment by JKorf** [comment]
Thanks for the report. This is because when the symbol parameter is sent the server response with a single object instead of a list, where for the UsdPerpetual and InverseFutures API's it still returns a list even when a symbol parameter is sent. This should be fixed in the latest release, there is now a separate `GetPositionAsync(symbol)` and `GetPositionsAsync()` method
