### ISSUE TITLE
UsdPerpetualApi.Trading.PlaceOrderAsync Error

### ISSUE THREAD

**Issue by khalasura** [JKorf/Bybit.Net#42]
When I excute PlaceOrderAsync(), the following error occurs.

 invalid request, please check your timestamp and recv_window param. req_timestamp: 1656380988818 server_timestamp: 1656380994889 recv_window: 5000

To solve this, change th recv_window parameter to 6000, the order request will be delayed by 6 seconds.

How to wolve this problem?

**Comment by klausbyskov** [comment]
It sounds to me like the time on your computer is out of sync. I would use an NTP server to automatically synchronise your local clock. The problem should disappear if your local computer/server and ByBit's servers are in agreement about what the current time is (within a 1 second threshold). I use automatic time sync on the servers I use to call the ByBit api, and I have never had this problem.

**Comment by JanKorf** [comment]
This is happening because of some weird behavior of the Bybit server in combination with the `Expect: 100-continue` header which is automatically send with requests from the .net framework. So assuming you're using .net framework, add `ServicePointManager.Expect100Continue = false;` at the start of your application. This prevents the `Expect` header from being send.

**Comment by JKorf** [comment]
This is happening because of some weird behavior of the Bybit server in combination with the Expect: 100-continue header which is automatically send with requests from the .net framework. So assuming you're using .net framework, add ServicePointManager.Expect100Continue = false; at the start of your application. This prevents the Expect header from being send.
